 # NewAge Launcher
 # Copyright (C) 2016 Jestus

 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.

 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # GNU General Public License for more details.

 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.

#--------------------------------#
#     AppVeyor Configuration     #
#--------------------------------#
 #------------------------------#
 #       NewAge Launcher        #
 #------------------------------#

version: 1.0.{build}
branches:
  only:
  - master
##install:
## - git submodule update --init --recursive
build:
  project: NewAgeLauncher.sln
  verbosity: minimal
deploy:
- provider: GitHub
  release: V1.0.2.7
  auth_token:
    secure: AaRUijs5QwQRA0b/D0OvrqvJVeTIBxH7Q5SWBobG71eBxDK5LzwHqx6lJnsjyZ1a
